spring:
  application:
    name: weather-service-b

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: host.minikube.internal:29092

server:
  port: 8081

grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    task1: INFO

weather:
  api:
    geo-url: ${WEATHER_GEO_URL:https://geocoding-api.open-meteo.com/v1/search}
    forecast-url: ${WEATHER_FORECAST_URL:https://api.open-meteo.com/v1/forecast}
    timezone: ${WEATHER_TIMEZONE:auto}
    temperature-unit: ${WEATHER_TEMPERATURE_UNIT:celsius}

  codes:
    0: clear
    1: partly_cloudy
    2: partly_cloudy
    3: cloudy
    45: fog
    48: fog
    51: drizzle
    53: drizzle
    55: drizzle
    56: freezing_drizzle
    57: freezing_drizzle
    61: rain
    63: rain
    65: rain
    66: freezing_rain
    67: freezing_rain
    71: snow
    73: snow
    75: snow
    77: snow_grains
    80: rain_showers
    81: rain_showers
    82: rain_showers
    85: snow_showers
    86: snow_showers
    95: thunderstorm
    96: thunderstorm_with_hail
    99: thunderstorm_with_hail