# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://postgres-service:5432/booksdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Liquibase - ???????? ??? ????????
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# JWT
app.jwt.secret=${JWT_SECRET:mySuperSecretKeyForJwtTokens}
app.jwt.expiration=3600000
# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Management endpoints for Kubernetes probes
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,metrics