apiVersion: v1
kind: Service
metadata:
  name: weather-service-a
spec:
  selector:
    app: weather-service-a
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service-b
spec:
  selector:
    app: weather-service-b
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-app
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30081
  type: NodePort