spring:
  application:
    name: weather-service-a

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  liquibase:
    enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: host.minikube.internal:29092
    consumer:
      group-id: weather-consumer

server:
  port: 8080
  address: 0.0.0.0

grpc:
  client:
    weather-service-b:
      address: static://${GRPC_SERVICE_B_HOST:localhost}:${GRPC_SERVICE_B_PORT:9090}
      negotiation-type: plaintext

logging:
  level:
    root: INFO
    task1: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info