spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
    default-schema: public

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: book-service-users
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082

app:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForJwtTokensThatIsVeryLongAndSecure1234567890!}
    expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    persist-authorization: true
    display-request-duration: true
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  show-actuator: true