# PostgreSQL Database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
# Liquibase - ???????? ??? ????????
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:host.minikube.internal:29092}
spring.kafka.consumer.group-id=book-service-users
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# JWT
app.jwt.secret=${JWT_SECRET:mySuperSecretKeyForJwtTokensThatIsVeryLongAndSecure1234567890!}
app.jwt.expiration=3600000
# Management endpoints for Kubernetes probes
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info,metrics